name: CDS MultiModule PR

env:
#  ENTANDO_GITHUB_TOOLS_VERSION: "v0.1.0"
  ENTANDO_GITHUB_TOOLS_VERSION: "ESB-703"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_PR_TITLE: ${{ github.event.pull_request.title }}
  GH_PR_NUMBER: ${{ github.event.pull_request.number }}
  GH_PR_RUN_NUMBER: ${{ github.run_number }}
  IMAGES_TO_BUILD: "Dockerfile:cds"
  ENTANDO_CRANE_VERSION: ${{ vars.ENTANDO_CRANE_VERSION || 'v0.10.0' }}
  GITHUB_REF: ${{ github.ref }}
  CARGO_TERM_COLOR: always

on:
  push:
    branches: [ "develop", "release/*" ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ "develop", "release/*", "main", "entando*" ]

jobs:
  #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
  #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  #  fmt:
  #    name: Rustfmt
  #    runs-on: ubuntu-latest
  #    steps:
  #      - uses: actions/checkout@v2
  #      - uses: actions-rs/toolchain@v1
  #        with:
  #          toolchain: stable
  #          override: true
  #          components: rustfmt
  #      - uses: actions-rs/cargo@v1
  #        with:
  #          command: fmt
  #          args: --all -- --check
  #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: -- -D warnings
  #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  coverage:
    name: Code coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # This installs the tarpaulin tool itself.
      - name: Install cargo-tarpaulin
        run: cargo install cargo-tarpaulin

      # This runs tarpaulin to generate the coverage report.
      - name: Run tarpaulin
        run: cargo tarpaulin --ignore-tests
  #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  publish:
    permissions:
      contents: read
      pull-requests: write

    runs-on: ubuntu-latest
    needs: [test, clippy]

    steps:
    - uses: actions/checkout@v4

    - name: Configure
      run: if [ -f ".github/configure" ]; then . .github/configure "publish"; fi

    - name: Build Docker image
      run: |
        .github/github-tools/docker.multiBuild \
          "${IMAGES_TO_BUILD}" \
          "${ARTIFACT_VERSION}" \
          "${{ vars.DOCKER_ORG }}" \
        ;

    - name: Publish Docker image
      run: |
        GH_DO_COMMENT=true \
          .github/github-tools/docker.multiPublish \
            "${IMAGES_TO_BUILD}" \
            "${ARTIFACT_VERSION}" \
            "${{ vars.DOCKER_ORG }}" \
            "${{ vars.DOCKER_REGISTRY }}" \
            "${{ secrets.DOCKER_USERNAME }}" \
            "${{ secrets.DOCKER_PASSWORD }}" \
            "${ARTIFACT_PUB_TYPE}" \
          ;
